### ISSUE TITLE
[Enhacement| Add api.mjs generation to setup

### ISSUE THREAD

**Issue by challmannsf** [SalesforceCommerceCloud/sfcc-sample-apps#136]
Hi,

it would be great if we can automate this manual step:

`Copy the packages/storefront-lwc/scripts/api.example.mjs file, save it as packages/storefront-lwc/scripts/api.mjs, and make sure it is added to your .gitignore file.`

This could streamline the setup to a mostly automated flow.
I'm thinking of sceneraios where we can spin up the app in a headless scenario (e.g for CI/CD purposes)

Possible solution

1. Add `.env` file to `.gitignore` project
2. Use `api.mjs` directly instead of `api.example.mjs`
3. Read all values from `.env` file in  `api.mjs`

I'm open for providing a PR if this makes any sense

**Comment by syedshehrozhussain** [comment]
@challmannsf thank you for the suggestion, I will bring it to the team to discuss if there is any ready why we would not want to do that. In the meanwhile, feel free to send in a PR if you get a chance. Thank you again for your suggestion and contribution.

**Comment by coopaq** [comment]
@challmannsf  The `.env` file with `.gitignore` would actually just be the same behavior as the current `api.mjs` since `api.mjs` is already in the `.gitignore`. If you want to read in environment variables instead of `api.mjs` look into packages/@sfcc-core/apiconfig/apiconfig.ts you will see that all your environment variables are read in. The environment variables are recommended for production deploys and `api.mjs` for development.

**Comment by challmannsf** [comment]
@coopaq  thanks! 
I was indeed looking for environment variables behvaior for ci/cd purposed.
One thing - you are pointing to a  `*.ts` file.
Are they also available?
