### ISSUE TITLE
[Question] Is this will made Storefront Reference Architecture deprecated (SFRA) ?

### ISSUE THREAD

**Issue by felixbillon** [SalesforceCommerceCloud/sfcc-sample-apps#204]
Hello everyone,

I juste begin reading SFCC documentation and I wondering if this sample application introduce the new way to use SFCC ? 

If no, what is the difference between this and SFRA ?

Thank you very much.

**Comment by p-mehta-sf** [comment]
Hi, 
Thanks for your question. 

Commerce Cloud wants to make it easy for development teams to get started building with our latest Commerce Platform innovations. The Storefront Sample Application provides an example implementation of these latest innovations, so that development teams can learn how to build their own storefront experiences on top of our headless platform using the NodeJS SDK and Salesforce Commerce API. 

Sample App is not a replacement for SFRA and is not meant to deprecate SFRA. Below are some points that differentiate sample app from SFRA 

* The sample application shows you a recommended approach for building a storefront against our new headless platform, but it is not a complete and fully functional storefront reference application. 
* The sample application is not a replacement for Storefront Reference Architecture (SFRA). It does not have full feature parity with a reference application like SFRA. Not every use-case is covered, and tested for performance
* The sample application, unlike SFRA, is not meant to be an out of the box production storefront application. It is meant to give you some guidance and understanding about how to get started, and help with adoption of our latest platform technologies, however, it is not intended to be a starting point to launch your storefront

I hope this helps!

**Comment by felixbillon** [comment]
Thanks a lot for this very clear explanation.

**Comment by thanhnhan2tn** [comment]
Hi @p-mehta-sf 
Is there any way to migrate current SFRA to this sfcc sample application?
