### ISSUE TITLE
Cannot read property 'customer_id' of undefined in runtime.js

### ISSUE THREAD

**Issue by jorgehernandezSF** [SalesforceCommerceCloud/sfcc-sample-apps#216]
On the latest master branch, this error is happening consistently when searching a category from the homepage: 

> Error in requestWithTokenRefresh() TypeError: Cannot read property 'customer_id' of undefined
> storefront-lwc:     at /Users/jorge.hernandez/Headless_projects/sfcc-sample-apps/packages/storefront-lwc/scripts/runtime.js:80:39
> storefront-lwc:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 

The API First workshop attendees figured out the fix: in runtime.js, line 80 (thanks guys!)
Replace:
            .customer_info.customer_id;
With
            .CustomerInfo.customerId;

That automatically restarts the app, and fixes the issue.  I'll do a PR to integration unless someone is already working on this.

**Comment by echessman** [comment]
@jorgehernandezSF Thank you for raising this issue/feedback. Due to the PR from @dorgelesn we have resolved this issue in our integration branch and will be available the next time we tag and merge to master. If you have any further questions and or concerns please do not hesitate to reach out again. Thank you!
